# Module configuration for METIS-based reordering techniques
name: "metis"
description: "METIS library for graph partitioning and reordering"
modules:
  - "metis/5.1.0"
  - "gcc/9.3.0"
  - "python/3.11"
environment:
  METIS_DLL: "${METIS_ROOT:-/usr/local}/lib/libmetis.so"
post_load:
  - "python -c 'import metis; print(f\"METIS available\")' 2>/dev/null || echo 'PyMetis not available'"