# Multiplication kernel parameter sets
cucsrspmm:
  gpus: 1
  time: "00:10:00"
  modules: "cuda_cusparse"
  params:
    - alpha: 1.0
      beta: 0.0
    - alpha: 2.0
      beta: 1.0

cucsrspmv:
  gpus: 1
  time: "00:10:00"
  modules: "cuda_cusparse"
  params:
    - alpha: 1.0
      beta: 0.0
      n_iterations: 10
    - alpha: 2.0
      beta: 1.0
      n_iterations: 10

cucbrspmm:
  gpus: 1
  time: "00:10:00"
  modules: "cuda_cusparse"
  params:
    - alpha: 1.0
      beta: 0.0
      block_size: 4
    - alpha: 2.0
      beta: 1.0
      block_size: 8

cucbrspmv:
  gpus: 1
  time: "00:10:00"
  modules: "cuda_cusparse"
  params:
    - alpha: 1.0
      beta: 0.0
      block_size: 4
      n_iterations: 10
    - alpha: 2.0
      beta: 1.1
      block_size: 8
      n_iterations: 10

smat:
  gpus: 1
  time: "00:15:00"
  modules: "cuda_cusparse"
  params:
    - n_mult: 1
      warmup_iterations: 1
      profiling_iterations: 10
    - n_mult: 2
      warmup_iterations: 2
      profiling_iterations: 20

mock:
  gpus: 0
  time: "00:05:00"
  modules: "basic"
  params:
    - alpha: 1.0

