# Reordering technique parameter sets
rcm:
  type: "2D"
  gpus: 0
  time: "00:10:00"
  params:
    - symmetric: true
    - symmetric: false

ro:
  type: "2D"
  gpus: 0
  time: "00:05:00"
  params:
    - mode: "reorder"
    - mode: "cluster"

identity:
  type: "1D"
  gpus: 0
  time: "00:01:00"
  params:
    - {}
