# Reordering technique parameter sets
rcm:
  type: "2D"
  gpus: 0
  time: "00:10:00"
  modules: "python_scipy"
  params:
    - {}

rcm_graphblas:
  type: "2D"
  gpus: 0
  time: "00:10:00"
  modules: "python_graphblas"
  params:
    - {}

ro:
  type: "2D"
  gpus: 0
  time: "00:05:00"
  modules: "basic"
  params:
    - {}

identity:
  type: "1D"
  gpus: 0
  time: "00:01:00"
  modules: "basic"
  params:
    - {}
